name: 'Staticmajor analyzer'
description: 'Analyze Go source code for defects'
branding:
  icon: 'check-square'
  color: 'blue'
inputs:
  packages:
    description: 'Go packages to analyze'
    required: true
    default: './...'
  fuzzy:
    description: 'Report leaks for types with Close or Stop methods'
    required: true
    default: 'false'
  tests:
    description: 'Analyze test files'
    required: true
    default: 'false'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/orijtech/staticmajor_action:latest'
  args:
    - '-resleak.fuzzy=${{ inputs.fuzzy }} -test=${{ inputs.tests  }} ${{ inputs.packages }}'
