name: 'Staticmajor analyzer'
description: 'Analyze Go source code for defects'
branding:
  icon: 'check-square'
  color: 'blue'
inputs:
  packages:
    description: 'Go packages to analyze'
    required: true
    default: './...'
  resleak:
    description: 'Report resource leaks'
    required: true
    default: 'true'
  fuzzy:
    description: 'Report leaks for types with Close or Stop methods'
    required: true
    default: 'false'
  httperroryzer:
    description: 'Report http.Error calls without return statements'
    required: true
    default: 'true'
  structslop:
    description: 'Report memory waste due to struct field ordering'
    required: true
    default: 'true'
  tests:
    description: 'Analyze test files'
    required: true
    default: 'true'
  generated:
    description: 'Analyze generated files'
    required: true
    default: 'true'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/orijtech/staticmajor_action:latest'
  args:
    - '-resleak=${{ inputs.resleak }} -resleak.fuzzy=${{ inputs.fuzzy }} -resleak.generated=${{ inputs.generated }} -httperroryzer=${{ inputs.httperroryzer }} -structslop=${{ inputs.structslop }} -test=${{ inputs.tests  }} ${{ inputs.packages }}'
